# FJ3.2: DB18 delayed ego dynamics parity against test/fixtures/fj3_ego.json
# (generated by tools/parity/gen_fj3_ego_fixtures.py in the reference venv
# `ddm-ref`: Python 3.9, numpy 1.20.0, gym 0.23.1, duckietown-gym-daffy
# 6.1.34, duckietown-world-daffy 6.4.3, PyGeometry-z6 2.1.5).
#
# Layers (user-required order), each compared at the policy's exactness level:
#   wheel  -> observed encoder ticks (round-half-to-even) and axis increments;
#   delayed command -> `get_commands_at` selection (idx, told, used) per tick;
#   acceleration -> `DynamicModel.model` x_dot_dot (pure scalar arithmetic);
#   body velocity -> longitudinal/angular + commands_se2 (≤2 ULP scalars,
#                    ≤1 ULP matrix entries);
#   SE(2) -> q1 = q0 * exp(dt * v) (matrix product ≤1 ULP / rtol 4eps);
#   world pose -> (pos, angle) via weird_from_cartesian (≤2 ULP).
# The tick trace is recorded from patched reference `DynamicModel.integrate`
# calls, i.e. exactly what the reference env executed.

using DuckietownDecisionModels
using Test
using JSON3

const FIXTURES_EGO = joinpath(pkgdir(DuckietownDecisionModels),
    "test", "fixtures", "fj3_ego.json")

fixtures_ego = JSON3.read(FIXTURES_EGO)

function unf(x)
    if x isa AbstractDict
        tag = x["nonfinite"]
        return tag == "nan" ? NaN :
            tag == "inf" ? Inf :
            tag == "-inf" ? -Inf : -0.0
    end
    return Float64(x)
end

ulps(a::Float64, b::Float64) = abs(reinterpret(Int64, a) - reinterpret(Int64, b))

# per-entry ≤2 ULP over a flat list of JSON numbers
ulpvec2(a, b) = all(ulps(unf(x), unf(y)) <= 2 for (x, y) in zip(a, b))

# per-entry ≤1 ULP or rtol=4eps (matrix products vs BLAS)
mat_close(a, b) = all(ulps(unf(x), unf(y)) <= 1 ||
    isapprox(unf(x), unf(y); rtol=4eps()) for (x, y) in zip(a, b))

# Julia matrix -> row-major flat vector
mat_rows(m::AbstractMatrix) = [m[i, j] for i in 1:size(m, 1) for j in 1:size(m, 2)]

# nested JSON array -> flat vector (row-major)
json_rows(x) = [unf(v) for row in x for v in row]

# nested JSON array -> Julia matrix (row-major)
json_mat(x) = [unf(x[i][j]) for i in 1:length(x), j in 1:length(x[1])]

@testset "FJ3.2 SE(2) primitives parity" begin
    for c in fixtures_ego.se2_cases
        lin = (unf(c.lin[1]), unf(c.lin[2]))
        ang = unf(c.ang)
        se2 = se2_from_linear_angular(lin, ang)
        @test mat_rows(se2) == [0.0, -ang, lin[1], ang, 0.0, lin[2], 0.0, 0.0, 0.0]
        @test mat_close(mat_rows(se2), json_rows(c.se2))
        @test mat_close(mat_rows(SE2_from_se2(unf(c.dt) .* se2)),
            json_rows(c.diff))
    end

    q0 = json_mat(fixtures_ego.init_q0)
    for c in fixtures_ego.mult_cases
        diff = json_mat(c.diff)
        q1 = se2_multiply(q0, diff)
        @test mat_close(mat_rows(q1), json_rows(c.q1))
        t, angle = translation_angle_from_SE2(q1)
        @test ulps(t[1], unf(c.t[1])) <= 2
        @test ulps(t[2], unf(c.t[2])) <= 2
        @test ulps(angle, unf(c.angle)) <= 2
    end
end

@testset "FJ3.2 world-frame conversion parity" begin
    gh = Int(fixtures_ego.grid_height)
    ts = unf(fixtures_ego.tile_size)
    for c in fixtures_ego.cart_cases
        pos = (unf(c.pos[1]), unf(c.pos[2]), unf(c.pos[3]))
        q = cartesian_from_weird(pos, unf(c.angle), gh, ts)
        @test mat_close(mat_rows(q), json_rows(c.q))
        pos2, angle2 = weird_from_cartesian(q, gh, ts)
        @test ulps(pos2[1], unf(c.pos_back[1])) <= 2
        @test ulps(pos2[2], unf(c.pos_back[2])) <= 2
        @test ulps(pos2[3], unf(c.pos_back[3])) <= 2
        @test ulps(angle2, unf(c.angle_back)) <= 2
    end
end

@testset "FJ3.2 DB18 model parity ($(length(fixtures_ego.model_cases)) cases)" begin
    p = db18_nominal()
    for c in fixtures_ego.model_cases
        xdd = db18_model(p, (unf(c.mL), unf(c.mR)), unf(c.u), unf(c.w))
        @test ulps(xdd[1], unf(c.x_dot_dot[1])) <= 2
        @test ulps(xdd[2], unf(c.x_dot_dot[2])) <= 2
    end
end

@testset "FJ3.2 delayed command selection parity" begin
    ts = [i / 30.0 for i in 0:9]
    cmds = [(0.5, 0.2), (-0.3, 0.7), (0.9, 0.1), (-0.8, -0.4), (0.2, 0.6),
        (0.0, 0.0), (0.7, -0.9), (-0.1, 0.3), (0.6, -0.6), (0.4, 0.4)]
    hist = [(ts[k], c[1], c[2]) for (k, c) in enumerate(cmds)]
    n_reg = 0
    n_irr = 0
    for c in fixtures_ego.delay_cases
        h = haskey(c, "grid") ? nothing : hist
        if h === nothing
            ts_irr = [0.0, 0.023, 0.059, 0.101, 0.148, 0.197, 0.250, 0.301]
            cmds_irr = [(0.1, 0.1), (-0.2, 0.2), (0.3, -0.3), (-0.4, 0.4),
                (0.5, -0.5), (-0.6, 0.6), (0.7, -0.7), (-0.8, 0.8)]
            h = [(ts_irr[k], c2[1], c2[2]) for (k, c2) in enumerate(cmds_irr)]
            n_irr += 1
        else
            n_reg += 1
        end
        sel = get_commands_at(h, unf(c.t))
        @test sel.idx == Int(c.i)
        @test ulps(sel.told, unf(c.told)) <= 2
        @test ulps(sel.used[1], unf(c.used[1])) <= 2
        @test ulps(sel.used[2], unf(c.used[2])) <= 2
    end
    @test n_reg + n_irr == length(fixtures_ego.delay_cases)
end

@testset "FJ3.2 tick chain parity (18 ticks, layered)" begin
    p = db18_nominal()
    gh = Int(fixtures_ego.grid_height)
    ts = unf(fixtures_ego.tile_size)
    pos = (unf(fixtures_ego.init_pos[1]), 0.0, unf(fixtures_ego.init_pos[3]))
    world = DuckieWorldState(
        initial_ego(pos, unf(fixtures_ego.init_angle), gh, ts),
        DuckieState[], [], small_loop_map(),
        StopMemory(false, 0, nothing, nothing), (1.0, 1.0), Int[], Bool[],
        MersenneTwister(53))

    # initial q0/v0 must match the reference reset state
    @test mat_close(mat_rows(world.ego.q0), json_rows(fixtures_ego.init_q0))
    @test mat_close(mat_rows(world.ego.v0), json_rows(fixtures_ego.init_v0))

    prev_axis = (0.0, 0.0)
    for f in fixtures_ego.ticks
        world = ego_tick(world, (unf(f.cmd[1]), unf(f.cmd[2])))
        e = world.ego

        # layer: delayed command selection index
        sel = get_commands_at(e.command_history, e.timestamp - EGO_DELAY)
        @test sel.idx == Int(f.delay_i)
        @test ulps(sel.told, unf(f.delay_told)) <= 2

        # layer: wheel axis increments + observed encoder ticks
        @test ulps(e.axis_left_rad - prev_axis[1], unf(f.d_axis_left)) <= 2
        @test ulps(e.axis_right_rad - prev_axis[2], unf(f.d_axis_right)) <= 2
        prev_axis = (e.axis_left_rad, e.axis_right_rad)
        lt = axis_observed_ticks(e.axis_left_rad, p)
        rt = axis_observed_ticks(e.axis_right_rad, p)
        @test lt == Int(f.left_ticks)
        @test rt == Int(f.right_ticks)
        @test ulps(lt * p.encoder_resolution_rad, unf(f.axis_left_obs)) <= 2
        @test ulps(rt * p.encoder_resolution_rad, unf(f.axis_right_obs)) <= 2

        # layer: body velocity (forward Euler of the acceleration)
        @test ulps(e.v_long, unf(f.longitudinal)) <= 2
        @test ulps(e.omega, unf(f.angular)) <= 2
        @test mat_close(mat_rows(e.v0), json_rows(f.commands_se2))

        # layer: SE(2) pose composition
        @test mat_close(mat_rows(e.q0), json_rows(f.q1))

        # layer: world pose
        @test ulps(e.pos[1], unf(f.world_pos[1])) <= 2
        @test ulps(e.pos[2], unf(f.world_pos[2])) <= 2
        @test ulps(e.pos[3], unf(f.world_pos[3])) <= 2
        @test ulps(e.angle, unf(f.world_angle)) <= 2

        # bookkeeping
        @test e.step_count == Int(f.tick)
        @test ulps(e.timestamp, unf(f.t)) <= 2
    end
end

@testset "FJ3.2 delay window spans decisions (frame_skip=6)" begin
    gh = Int(fixtures_ego.grid_height)
    ts = unf(fixtures_ego.tile_size)
    pos = (unf(fixtures_ego.init_pos[1]), 0.0, unf(fixtures_ego.init_pos[3]))
    world = DuckieWorldState(
        initial_ego(pos, unf(fixtures_ego.init_angle), gh, ts),
        DuckieState[], [], small_loop_map(),
        StopMemory(false, 0, nothing, nothing), (1.0, 1.0), Int[], Bool[],
        MersenneTwister(53))
    # one full decision (frame_skip=6): the applied command must still be
    # u0 = (0, 0) for the first 4 ticks and commands[0] from tick 5 on
    used = []
    for k in 1:6
        world = ego_tick(world, (0.7, 0.4))
        sel = get_commands_at(world.ego.command_history,
            world.ego.timestamp - EGO_DELAY)
        push!(used, sel.used)
    end
    @test used[1:4] == fill((0.0, 0.0), 4)
    @test used[5:6] == fill((0.7, 0.4), 2)
end
