# FJ3.7: full one-decision transition chain parity against
# test/fixtures/fj37_transition.json — generated by the REAL
# `DuckieMDPEnv.step` / `ContinuousDuckieMDPEnv.step` (built by the reference
# `build_env`/`build_continuous_env` from the actual experiment YAMLs), never
# by a hand-reconstructed chain.
#
# 24 scenarios / 1250 decisions covering: all 7 macro actions, the continuous
# action-space key points (zero, extremes, interior, an out-of-range clip
# case), scripted lane-following rollouts, and config-variant scenarios that
# reach every TerminationReason (duck_collision, other_collision, timeout,
# offroad, goal, in_progress) and every EventFlags bit (incl. full_stop,
# passed_stop, stop_violation via a reachable-sign variant).
#
# Replay: the Julia side rebuilds the initial world from the recorded reset
# latent and drives `simulate_decision` with the recorded action sequence;
# every wrapper output is compared per decision. Numerical tolerances follow
# the FJ3 conventions (<= 3 ULP positions over multi-decision chains; the
# conditioning-aware comparator for acos-derived angles; documented libm
# deviations only).

using DuckietownDecisionModels
using Test
using JSON3
using Random

const FIXTURES_TR = joinpath(pkgdir(DuckietownDecisionModels),
    "test", "fixtures", "fj37_transition.json")
const DUCKDUCK_POLICIES = joinpath(pkgdir(DuckietownDecisionModels),
    "..", "duckduck", "policies")

fixtures_tr = JSON3.read(FIXTURES_TR)

function unf_tr(x)
    x === nothing && return nothing
    if x isa AbstractDict
        tag = x["nonfinite"]
        return tag == "nan" ? NaN :
            tag == "inf" ? Inf :
            tag == "-inf" ? -Inf : -0.0
    end
    return Float64(x)
end

ulps_tr(a::Float64, b::Float64) =
    abs(reinterpret(Int64, a) - reinterpret(Int64, b))

sc_tr(a, b; n=3) = a == b ||
    (a isa Float64 && b !== nothing && ulps_tr(a, unf_tr(b)) <= n)

# acos/atan-derived angles: <= n ULP or the conditioning-scaled bound
# (see test_fj3_obs.jl / docs/src/validation/FJ3_STATUS.md)
sc_angle_tr(a::Float64, b; n=3) = sc_tr(a, b; n) ||
    abs(a - unf_tr(b)) <= 8 * eps(1.0) / max(abs(sin(a)), 1e-6)

# reward components: ULP-tight with a tiny absolute fallback for terms that
# compound v (norm), cos(phi) (libm), and quadratic penalties
sc_rew(a::Float64, b; n=8) = sc_tr(a, b; n) || abs(a - unf_tr(b)) <= 1e-11

const REASONS_TR = Dict(
    "duck_collision" => DUCK_COLLISION,
    "other_collision" => OTHER_COLLISION,
    "timeout" => TIMEOUT,
    "offroad" => OFFROAD,
    "goal" => GOAL,
    "in_progress" => IN_PROGRESS,
)

tuple3(v) = (unf_tr(v[1]), unf_tr(v[2]), unf_tr(v[3]))

function duck_from_tr(dj)
    corners = [(unf_tr(dj.corners[i][1]), unf_tr(dj.corners[i][2]))
        for i in 1:4]
    norm_m = Float64[unf_tr(dj.norm[i][j]) for i in 1:2, j in 1:2]
    return DuckieState(tuple3(dj.pos), tuple3(dj.center), tuple3(dj.start),
        unf_tr(dj.angle), tuple3(dj.heading), unf_tr(dj.vel),
        Bool(dj.visible), Bool(dj.active), unf_tr(dj.wait), unf_tr(dj.time),
        unf_tr(dj.walk_distance), unf_tr(dj.scale), unf_tr(dj.safety_radius),
        tuple3(dj.min_coords), tuple3(dj.max_coords), corners, norm_m)
end

function model_for_scenario(s)
    path = joinpath(DUCKDUCK_POLICIES, String(s.config), "training_config.yaml")
    cfg = load_config(path)
    m = DuckieTransitionModel(cfg)
    haskey(s, :meta) || return m
    meta = s.meta
    goal = haskey(meta, :goal_tile) ?
        (Int(meta.goal_tile[1]), Int(meta.goal_tile[2])) : m.goal_tile
    duck_cfg = m.duck_cfg
    if haskey(meta, :duck_overrides) &&
        haskey(meta.duck_overrides, :max_crossings_per_episode)
        d = duck_cfg
        duck_cfg = DuckControllerConfig(p_cross=d.p_cross,
            make_dynamic=d.make_dynamic, require_duck=d.require_duck,
            inject_if_missing=d.inject_if_missing, spawn_pos=d.spawn_pos,
            spawn_rotate=d.spawn_rotate, spawn_height=d.spawn_height,
            walk_distance=d.walk_distance,
            trigger_min_ego_distance=d.trigger_min_ego_distance,
            trigger_max_ego_distance=d.trigger_max_ego_distance,
            spawn_on_ego_proximity=d.spawn_on_ego_proximity,
            max_crossings_per_episode=Int(
                meta.duck_overrides.max_crossings_per_episode),
            repeat_rearm_distance=d.repeat_rearm_distance,
            inject_stop_if_missing=d.inject_stop_if_missing,
            require_stop=d.require_stop)
    end
    return DuckieTransitionModel(m.action_cfg, m.state_cfg, m.reward_cfg,
        duck_cfg, m.continuous_cfg, m.frame_skip, m.max_steps, goal)
end

function map_for_scenario(s)
    if haskey(s, :meta) && haskey(s.meta, :sign_desc)
        sd = s.meta.sign_desc
        base = small_loop_map(with_stop_sign=false)
        sign = interpret_object_desc(kind=:sign_stop, pos=tuple3(sd.pos),
            rotate_deg=unf_tr(sd.rotate_deg), height=unf_tr(sd.height),
            static=true)
        return RoadMap(base.name, base.tile_size, base.grid, [sign])
    end
    return small_loop_map()
end

function world_for_scenario(s)
    init = s.init
    map = map_for_scenario(s)
    ego = initial_ego(tuple3(init.pos), unf_tr(init.angle),
        size(map.grid, 1), map.tile_size)
    ducks = [duck_from_tr(dj) for dj in init.ducks]
    signs = [StopSignState(tuple3(sg.pos), unf_tr(sg.angle))
        for sg in init.signs]
    lid = init.last_stop_id === nothing ? nothing : Int(init.last_stop_id)
    ld = init.last_d_stop === nothing ? nothing : unf_tr(init.last_d_stop)
    return DuckieWorldState(ego, ducks, signs, map,
        StopMemory(false, 0, lid, ld),
        (unf_tr(init.fallback[1]), unf_tr(init.fallback[2])),
        Int[Int(v) for v in init.crossings_started],
        Bool[Bool(v) for v in init.crossing_armed],
        MersenneTwister(0))
end

action_for(s, d) = String(s.kind) == "discrete" ? Int(d.action) :
    DuckieAction(unf_tr(d.action[1]), unf_tr(d.action[2]))

function compare_decision(s, d, r::TransitionResult)
    out = d.out
    for i in 1:2
        @test Float64(r.wheel_commands[i]) == unf_tr(out.wheels[i])
    end
    sp = r.sp
    for i in 1:3
        @test sc_tr(sp.ego.pos[i], out.pos[i])
    end
    @test sc_angle_tr(sp.ego.angle, out.angle)
    @test sc_tr(sp.ego.speed, out.speed; n=6)
    @test sp.ego.step_count == Int(out.step_count)

    raw = r.raw_state
    @test sc_tr(raw.d, out.raw.d)
    @test sc_angle_tr(raw.phi, out.raw.phi)
    @test sc_tr(raw.v, out.raw.v; n=6)
    @test Int(raw.tile) == Int(out.raw.tile)
    if out.raw.d_stop === nothing
        @test raw.d_stop === nothing
    else
        @test raw.d_stop !== nothing && sc_tr(raw.d_stop, out.raw.d_stop; n=6)
    end
    @test raw.sigma_stop == Bool(out.raw.sigma_stop)
    @test Int(raw.duck) == Int(out.raw.duck)

    mem = sp.stop_memory
    expected_id = out.stop_id === nothing ? nothing : Int(out.stop_id)
    @test mem.last_stop_id == expected_id
    @test mem.sigma_stop == Bool(out.sigma)
    @test mem.hold_steps == Int(out.hold_steps)

    ev = r.events
    @test ev.collision_duck == Bool(out.events.collision_duck)
    @test ev.other_collision == Bool(out.events.other_collision)
    @test ev.offroad == Bool(out.events.offroad)
    @test ev.timeout == Bool(out.events.timeout)
    @test ev.stop_violation == Bool(out.events.stop_violation)
    @test ev.full_stop == Bool(out.events.full_stop)
    @test ev.passed_stop == Bool(out.events.passed_stop)
    @test ev.goal == Bool(out.events.goal)

    rw = r.reward
    @test sc_rew(rw.progress, out.reward.progress)
    @test sc_rew(rw.lateral, out.reward.lateral)
    @test sc_rew(rw.heading, out.reward.heading)
    @test sc_rew(rw.time, out.reward.time)
    @test sc_rew(rw.pedestrian, out.reward.pedestrian)
    @test sc_rew(rw.stagnation, out.reward.stagnation)
    @test sc_rew(rw.stop_approach, out.reward.stop_approach)
    @test sc_rew(rw.steering, out.reward.steering)
    @test sc_rew(rw.events, out.reward.events)
    @test sc_rew(rw.total, out.reward.total)

    @test r.reason == REASONS_TR[String(out.reason)]
    @test r.terminated == Bool(out.terminated)
    @test r.truncated == Bool(out.truncated)

    for i in 1:3
        @test sc_tr(sp.ducks[1].center[i], out.duck.center[i])
    end
    @test sp.ducks[1].pedestrian_active == Bool(out.duck.active)
    @test sc_tr(sp.ducks[1].vel, out.duck.vel)
    @test sp.crossings_started == Int[Int(v) for v in out.crossings_started]
    @test sp.crossing_armed == Bool[Bool(v) for v in out.crossing_armed]

    if haskey(out, :cont)
        cont = r.continuous_state
        @test sc_tr(cont.kappa, out.cont.kappa; n=6)
        @test cont.stop_present == Bool(out.cont.stop_present)
        @test cont.duck_present == Bool(out.cont.duck_present)
        @test sc_tr(cont.duck_longitudinal, out.cont.duck_longitudinal; n=6)
        @test sc_tr(cont.duck_lateral, out.cont.duck_lateral; n=6)
        @test sc_tr(cont.duck_v_longitudinal_relative,
            out.cont.duck_v_longitudinal_relative; n=6)
        @test sc_tr(cont.duck_v_lateral_relative,
            out.cont.duck_v_lateral_relative; n=6)
        @test cont.duck_active == Bool(out.cont.duck_active)
        @test cont.duck_crossing_available ==
            Bool(out.cont.duck_crossing_available)
        @test sc_tr(cont.stop_hold_progress, out.cont.stop_hold_progress)
    end
end

@testset "FJ3.7 one-decision chain parity ($(length(fixtures_tr.scenarios)) scenarios)" begin
    for s in fixtures_tr.scenarios
        model = model_for_scenario(s)
        world = world_for_scenario(s)
        rng = MersenneTwister(2024)
        @testset "$(s.name)" begin
            for d in s.decisions
                r = simulate_decision(model, world, action_for(s, d), rng)
                compare_decision(s, d, r)
                world = r.sp
            end
        end
    end
end

@testset "FJ3.7 branch purity + aliasing" begin
    s = first(sc for sc in fixtures_tr.scenarios if String(sc.name) == "mixed")
    model = model_for_scenario(s)
    world = world_for_scenario(s)
    rng = MersenneTwister(2024)
    # advance a few decisions so the delay buffer and duck state are non-trivial
    for d in s.decisions[1:10]
        world = simulate_decision(model, world, action_for(s, d), rng).sp
    end
    snap = deepcopy(world)

    sp1 = simulate_decision(model, world, 0, MersenneTwister(7)).sp
    sp2 = simulate_decision(model, world, 2, MersenneTwister(7)).sp

    # the parent state is untouched
    @test world.ego.pos == snap.ego.pos
    @test world.ego.angle == snap.ego.angle
    @test world.ego.step_count == snap.ego.step_count
    @test world.ego.command_history == snap.ego.command_history
    @test world.ego.q0 == snap.ego.q0
    @test world.ego.v0 == snap.ego.v0
    @test length(world.ducks) == length(snap.ducks)
    @test world.ducks[1].center == snap.ducks[1].center
    @test world.ducks[1].obj_corners == snap.ducks[1].obj_corners
    @test world.ducks[1].pedestrian_active == snap.ducks[1].pedestrian_active
    @test world.stop_memory.sigma_stop == snap.stop_memory.sigma_stop
    @test world.stop_memory.hold_steps == snap.stop_memory.hold_steps
    @test world.crossings_started == snap.crossings_started
    @test world.lane_fallback == snap.lane_fallback

    # the two branches genuinely diverged
    @test sp1.ego.pos != sp2.ego.pos

    # aliasing: no successor may share mutable containers with the parent
    for sp in (sp1, sp2)
        @test sp.ego !== world.ego
        @test sp.ego.command_history !== world.ego.command_history
        @test sp.ego.q0 !== world.ego.q0
        @test sp.ego.v0 !== world.ego.v0
        @test sp.ducks !== world.ducks
        @test sp.ducks[1].obj_corners !== world.ducks[1].obj_corners
        @test sp.ducks[1].obj_norm !== world.ducks[1].obj_norm
        @test sp.crossings_started !== world.crossings_started
        @test sp.crossing_armed !== world.crossing_armed
    end
    @test sp1.ducks !== sp2.ducks
    @test sp1.ego.command_history !== sp2.ego.command_history
end

@testset "FJ3.7 RNG-B determinism + frame-skip + delay memory" begin
    s = first(sc for sc in fixtures_tr.scenarios if String(sc.name) == "mixed")
    model = model_for_scenario(s)
    world = world_for_scenario(s)
    rng = MersenneTwister(2024)
    for d in s.decisions[1:8]
        world = simulate_decision(model, world, action_for(s, d), rng).sp
    end

    # RNG-B: same state, same action, same seed -> identical results
    ra = simulate_decision(model, world, 1, MersenneTwister(99))
    rb = simulate_decision(model, world, 1, MersenneTwister(99))
    @test ra.sp.ego.pos == rb.sp.ego.pos
    @test ra.sp.ego.angle == rb.sp.ego.angle
    @test ra.reward.total == rb.reward.total
    @test ra.sp.ducks[1].center == rb.sp.ducks[1].center
    @test ra.reason == rb.reason

    # frame-skip: one decision is exactly frame_skip physics ticks
    @test ra.sp.ego.step_count == world.ego.step_count + model.frame_skip

    # delayed dynamics: the trimmed window (0.15 s ≈ 4.5 ticks, SHORTER than
    # one 6-tick decision) must still serve the NEXT decision's first tick,
    # whose selection time T + dt - 0.15 lies inside THIS decision — i.e. the
    # first physics tick after a decision boundary is driven by a command
    # issued during the previous decision, which is why the command history
    # is state (Markov sufficiency of DuckieWorldState).
    @test !isempty(ra.sp.ego.command_history)
    T = ra.sp.ego.timestamp
    @test minimum(h[1] for h in ra.sp.ego.command_history) <=
        T + EGO_DT - EGO_DELAY
    @test all(h[1] < T for h in ra.sp.ego.command_history)
end
